services:
  - type: web
    name: react-a11y-test
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
